#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx

# Firewall setting: Allow Nginx to serve on HTTP
ufw allow 'Nginx HTTP'

# Override the default index file served as home page
echo "Holberton School" >> /home/ubuntu/index.html

#Give the user  ownership to website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Redirect to /redirect_me to a youtube video
sed -i '49i\location /redirect_me {return 301 https://youtube.com/@emma_obelenge?si=x6uGvH6HZ9hoU-CH;}

# Setup 404 page
echo "Ceci n'est pas une page\n" >> /var/www/html/404.html
sed -i '60i\error_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx start
