#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx

# Firewall setting: Allow Nginx to serve on HTTP
ufw allow 'Nginx HTTP'

# Override the default index file served as home page
echo "Hello World!" | sudo tee /var/www/html/index.html

#Give the user  ownership to website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Redirect to /redirect_me to a youtube video
sed -i '49i\\tlocation /redirect_me {return 301 https://youtube.com/@emma_obelenge?si=x6uGvH6HZ9hoU-CH;}' /etc/nginx/sites-available/default

# Setup 404 page
echo "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html
sed -i '49i\\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Setup custom http header (X-Served-By)
sed -i '/server_name _/a \\tadd_header X-Served-By \"\$HOSTNAME\";' /etc/nginx/sites-available/default

# Restarting ninx server
service nginx restart
