#!/usr/bin/env bash
# balancer install
sudo apt-get -y update
sudo apt-get install -y haproxy
echo "
frontend obelenge
    bind *:80
    mode http
    default_backend backend_server

backend backend_server
    balance roundrobin
    server 301399-web-01 35.153.17.101:80 check
    server 301399-web-02 34.207.58.252:80 check " >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
