#!/usr/bin/env bash
#Script that displays numbers from 1 to 100

j=0
i=1
list=()

while [ $i -le 100 ]
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		list[j]="FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		list[j]="Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		list[j]="Buzz"
	else
		list[j]="$i"
	fi
	i=$((i + 1))
	j=$((j + 1))
done

for item in "${list[@]}"
do
	echo "$item"
done
