#!/usr/bin/env bash
#Script that displays numbers from 1 to 100

i=0
list=()
while [ $i -lt 20 ]
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		list[$i]="FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		list[$i]="Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		list[$i]="Buzz"
	else
		list[$i]="$i"
	fi
	i=$((i + 1))
done

for item in "${list[@]}"
do
	echo "$item"
done
