#!/usr/bin/env bash
#Script that displays numbers from 1 to 100

i=1
list=()
while [ $i -le 20 ]
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		list[$i - 1]="FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		list[$i - 1]4="Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		list[$i- 1]="Buzz"
	else
		list[$i -1]="$i"
	fi
	i=$((i + 1))
done

for item in "${list[@]}"
do
	echo "$item"
done
