#!/usr/bin/env bash
#bash script for printing Best School 10 times with while loop

i="0"
while [ "$i" -le 10 ]
do
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
